version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: vcdsvisualizer_dev
    environment:
      - PYTHONPATH=/app
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vcdsvisualizer_prod
    environment:
      - PYTHONPATH=/app
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=database
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  database:
    image: postgres:15
    container_name: vcdsvisualizer_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"