FROM postgres:latest

ENV POSTGRES_DB=autolink_db
ENV POSTGRES_USER=autolink_user
ENV POSTGRES_PASSWORD=securepassword

# COPY ./scripts/init.sql /docker-entrypoint-initdb.d/init.sql
# COPY ./scripts/seed.sql /docker-entrypoint-initdb.d/seed.sql

EXPOSE 5432